spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_mtl?characterEncoding=utf8&useSSL=false
      username: root
      password: wangtao

# \u8BBE\u7F6E MyBatis \u7684 xml \u4FDD\u5B58\u8DEF\u5F84
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration: # \u914D\u7F6E\u6253\u5370 MyBatis \u6267\u884C\u7684 SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# \u914D\u7F6E\u6253\u5370 MyBatis \u6267\u884C\u7684 SQL
logging:
  level:
    com:
      example:
        demo: debug
