spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mtldb?characterEncoding=utf8&useSSL=false
      username: root
      password: wangtao

# 设置 MyBatis 的 xml 保存路径
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml #在 mtl-dao 子工程
  configuration: # 配置打印 MyBatis 执行的 SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.wt.mtl.beans  #在 mtl-bean子工程
# 配置打印 MyBatis 执行的 SQL
logging:
  level:
    com:
      example:
        demo: debug
