
# \u914D\u7F6E\u6570\u636E\u5E93\u7684\u8FDE\u63A5\u5B57\u7B26\u4E32
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wms?characterEncoding=utf8&useSSL=false
    username: root
    password: wangtao
    driver-class-name: com.mysql.cj.jdbc.Driver
# \u8BBE\u7F6E MyBatis \u7684 xml \u4FDD\u5B58\u8DEF\u5F84
mybatis-plus:
  configuration: # \u914D\u7F6E\u6253\u5370 MyBatis \u6267\u884C\u7684 SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# \u914D\u7F6E\u6253\u5370 MyBatis \u6267\u884C\u7684 SQL
logging:
  level:
    com:
      example:
        demo: debug
server:
  port: 9090
