server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce_platform?characterEncoding=utf8&useSSL=false
    username: root
    password: wangtao
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
     prefix: /
     suffix: jsp

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置视图解析器


