server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wms?characterEncoding=utf8&useSSL=false
    username: root
    password: wangtao
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
